"use client";

import { useState } from "react";
import RazorpayButton from "@/components/RazorpayButton";

export default function CareerGuidance() {
  const [step, setStep] = useState(1);
  const [name, setName] = useState("");
  const [city, setCity] = useState("Latur");
  const [currentClass, setCurrentClass] = useState("10th");
  const [percentage, setPercentage] = useState("");
  const [favSubject, setFavSubject] = useState("");
  const [budget, setBudget] = useState("Moderate (Local/Pune)");
  const [mathAptitude, setMathAptitude] = useState(3);
  const [healthcareInterest, setHealthcareInterest] = useState(3);
  const [businessMindset, setBusinessMindset] = useState(3);
  const [govtJobPreference, setGovtJobPreference] = useState(3);
  const [isPremiumUnlocked, setIsPremiumUnlocked] = useState(false);

  const goToStep2 = (e) => { e.preventDefault(); if (name && percentage) setStep(2); };
  const goToStep3 = () => setStep(3);
  const handlePaymentSuccess = () => setIsPremiumUnlocked(true);

  // Generate report HTML
  const getStrengthsList = () => {
    const items = [];
    if (mathAptitude >= 4) items.push("• Strong analytical and logical thinking.");
    if (healthcareInterest >= 4) items.push("• Interest in healthcare and helping others.");
    if (businessMindset >= 4) items.push("• Entrepreneurial mindset.");
    if (govtJobPreference >= 4) items.push("• Desire for government job stability.");
    if (parseFloat(percentage) >= 75) items.push(`• Excellent academic record (${percentage}%).`);
    if (favSubject) items.push(`• Deep interest in ${favSubject}.`);
    if (items.length === 0) items.push("• Balanced skillset.");
    return items;
  };
  const getWeaknessesList = () => {
    const items = [];
    const pct = parseFloat(percentage);
    if (pct < 60) items.push(`• Academic score of ${pct}% may need improvement.`);
    if (budget !== "High") items.push(`• Budget constraint (${budget}) may limit options.`);
    if (mathAptitude < 3) items.push("• Lower interest in mathematics.");
    if (items.length === 0) items.push("• No major weaknesses.");
    return items;
  };
  const getOpportunitiesList = () => {
    const items = ["• Growing IT hubs in Pune, Mumbai.", "• Expanding healthcare sector.", "• Government digital initiatives.", "• Online learning platforms."];
    if (budget !== "High") items.push("• Scholarships available for meritorious students.");
    return items;
  };
  const getThreatsList = () => ["• High competition for top colleges.", "• Automation may replace routine jobs.", "• Economic fluctuations."];
  const getCollegeRecommendations = () => {
    const cols = [];
    if (mathAptitude >= 4) cols.push("• Engineering: COEP Pune, VJTI Mumbai.");
    if (healthcareInterest >= 4) cols.push("• Pharmacy: ICT Mumbai, Bharati Vidyapeeth.");
    if (businessMindset >= 4) cols.push("• Commerce/Management: JBIMS, Symbiosis Pune.");
    if (govtJobPreference >= 4) cols.push("• General degree with MPSC focus: Fergusson College.");
    if (cols.length === 0) cols.push("• Any recognised university in Maharashtra.");
    return cols;
  };

  const generateReportHTML = () => {
    return `<!DOCTYPE html>
    <html>
    <head><meta charset="UTF-8"><title>SWOT Report</title><style>body{font-family:Arial;padding:20px;max-width:800px;margin:0 auto;} h1{color:#1E3A8A;} h2{margin-top:20px;} @media print{body{margin:0;padding:20px;}}</style></head>
    <body>
      <h1>Career SWOT Analysis Report</h1>
      <p>Prepared for: <strong>${name || "Student"}</strong> | ${city} | ${currentClass} | ${percentage}%</p>
      <hr/>
      <h2>💪 Strengths</h2><ul>${getStrengthsList().map(s=>`<li>${s}</li>`).join("")}</ul>
      <h2>📉 Weaknesses</h2><ul>${getWeaknessesList().map(w=>`<li>${w}</li>`).join("")}</ul>
      <h2>🌱 Opportunities</h2><ul>${getOpportunitiesList().map(o=>`<li>${o}</li>`).join("")}</ul>
      <h2>⚠️ Threats</h2><ul>${getThreatsList().map(t=>`<li>${t}</li>`).join("")}</ul>
      <h2>🎯 Action Plan</h2>
      <ul><li>Short-term: Enrol in online certifications related to ${favSubject || "your field"}.</li><li>Medium-term: Prepare for entrance exams (${mathAptitude>=4?"JEE":healthcareInterest>=4?"NEET":businessMindset>=4?"IPMAT":"common tests"}).</li><li>Long-term: Pursue degree with internships in Pune/Mumbai.</li></ul>
      <h2>📚 Recommended Colleges</h2><ul>${getCollegeRecommendations().map(c=>`<li>${c}</li>`).join("")}</ul>
      <p>Generated by AyushNexa AI Career Consultant.</p>
    </body></html>`;
  };

  const handlePrint = () => {
    const win = window.open();
    win?.document.write(generateReportHTML());
    win?.document.close();
    win?.print();
  };

  return (
    <div className="min-h-screen bg-slate-50 p-4">
      <div className="max-w-2xl mx-auto bg-white p-6 rounded shadow">
        {step === 1 && (
          <form onSubmit={goToStep2}>
            <h2 className="text-xl font-bold mb-4">Student Profile</h2>
            <input placeholder="Full Name" className="w-full border p-2 mb-2" value={name} onChange={e=>setName(e.target.value)} required />
            <input placeholder="City" className="w-full border p-2 mb-2" value={city} onChange={e=>setCity(e.target.value)} required />
            <select className="w-full border p-2 mb-2" value={currentClass} onChange={e=>setCurrentClass(e.target.value)}>
              <option>10th</option><option>12th_Science</option><option>12th_Commerce</option><option>Graduate</option>
            </select>
            <input placeholder="Percentage" type="number" className="w-full border p-2 mb-2" value={percentage} onChange={e=>setPercentage(e.target.value)} required />
            <input placeholder="Favorite Subject" className="w-full border p-2 mb-2" value={favSubject} onChange={e=>setFavSubject(e.target.value)} />
            <select className="w-full border p-2 mb-4" value={budget} onChange={e=>setBudget(e.target.value)}>
              <option>Low</option><option>Moderate (Local/Pune)</option><option>High</option>
            </select>
            <button type="submit" className="w-full bg-blue-600 text-white p-2 rounded">Next</button>
          </form>
        )}
        {step === 2 && (
          <div>
            <h2 className="text-xl font-bold mb-4">Aptitude Assessment (1-5)</h2>
            {[ {label:"Math & Logical", val:mathAptitude, set:setMathAptitude},
               {label:"Medical/Healthcare", val:healthcareInterest, set:setHealthcareInterest},
               {label:"Business/Sales", val:businessMindset, set:setBusinessMindset},
               {label:"Government Job", val:govtJobPreference, set:setGovtJobPreference} ].map(item=>(
              <div key={item.label} className="mb-4">
                <label>{item.label}: {item.val}</label>
                <input type="range" min="1" max="5" className="w-full" value={item.val} onChange={e=>item.set(parseInt(e.target.value))} />
              </div>
            ))}
            <button onClick={goToStep3} className="w-full bg-blue-600 text-white p-2 rounded">Analyze</button>
          </div>
        )}
        {step === 3 && (
          <div>
            <h2 className="text-xl font-bold mb-4">Results</h2>
            <div className="mb-4">
              <p><strong>Name:</strong> {name}</p>
              <p><strong>Percentage:</strong> {percentage}%</p>
            </div>
            {!isPremiumUnlocked ? (
              <div className="text-center p-4 border rounded">
                <p className="mb-2">Unlock full 15-page SWOT report for ₹199</p>
                <RazorpayButton amount={199} productName="Career Guidance" onSuccess={handlePaymentSuccess} label="Unlock ₹199" />
              </div>
            ) : (
              <button onClick={handlePrint} className="w-full bg-green-600 text-white p-2 rounded">Download SWOT Report (PDF)</button>
            )}
          </div>
        )}
      </div>
    </div>
  );
}